// https://github.com/awalterschulze/katydid/blob/master/asm/asm.bnf

!whitespace: ' ' | '\t' | '\n' | '\r' ;
_letter : 'a'-'z' | 'A'-'Z' ;

_digit : '0'-'9' ;

_idchar : _letter | _digit | '_' ;

id : (_letter | '_') {_idchar} ;

_inittype : ("launchctl" | "upstart" | "systemd" | "init.d" | "runit")
_entity : ("service" | "system")
_preamble : 'inspect' _inittype _entity


ConfSpec :
    "inspect" _inittype _entity id                << ast.NewInspect($1, $2, $3), nil >>
  | "inspect" _entity id                          << ast.NewInspect(nil, $1, $2), nil >>


Stmt:
  "if" metric operator value "then" action      << ast.NewCheck($1, $2, $3, $5), nil >>


