#!/bin/sh

set -e

# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
# https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s04s05.html
if [ "$1" = "purge" ]; then
    rm -rf /etc/inspeqtor
fi
rm -f /var/run/inspeqtor.sock
rm -f /etc/init/inspeqtor.conf
rm -f /etc/systemd/system/inspeqtor.service
rm -f /usr/lib/systemd/system/inspeqtor.service
rm -f /lib/systemd/system/inspeqtor.service
