#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -rf /etc/inspeqtor
fi
rm -f /var/run/inspeqtor.sock
rm -f /etc/init/inspeqtor.conf
rm -f /etc/systemd/system/inspeqtor.service
rm -f /usr/lib/systemd/system/inspeqtor.service
