#!/bin/sh

set -e

if [ ! -d /etc/inspeqtor ]; then
  mkdir /etc/inspeqtor
fi

if [ ! -d /etc/inspeqtor/conf.d ]; then
  cp -r /usr/share/inspeqtor/conf.d /etc/inspeqtor/conf.d

  # on Ubuntu, allow any adms to edit inqs
  if ! chown -R root:adm /etc/inspeqtor/conf.d ; then
    true # ignore if adm doesn't exist
  fi
fi

if [ ! -f /etc/inspeqtor/inspeqtor.conf ]; then
  cp /usr/share/inspeqtor/inspeqtor.conf /etc/inspeqtor
  # passwords in here, root readable only.
  chmod 600 /etc/inspeqtor/inspeqtor.conf
fi

CMD="sudo start inspeqtor"
if [ ! -d /etc/systemd ]; then
  CMD="sudo systemctl start inspeqtor"
  cp -r /usr/share/inspeqtor/systemd/inspeqtor.service /usr/lib/systemd/system/inspeqtor.service

  systemctl daemon-reload
  systemctl enable inspeqtor
  systemctl restart inspeqtor
fi

cat <<"TXT"
 _                            _
(_)_ __  ___ _ __   ___  __ _| |_ ___  _ __
| | '_ \/ __| '_ \ / _ \/ _  | __/ _ \| '__|
| | | | \__ \ |_) |  __/ (_| | || (_) | |
|_|_| |_|___/ .__/ \___|\__, |\__\___/|_|
            |_|            |_|


Thank you for installing Inspeqtor!

TXT

echo Please configure your alert settings in /etc/inspeqtor/inspeqtor.conf and then start Inspeqtor with \"$CMD\".
exit 0
