#!/bin/sh
set -e

if [ -e /etc/systemd/system/inspeqtor.service ]; then
  echo Stopping and disabling systemd service
  systemctl stop inspeqtor
  systemctl disable inspeqtor
fi

if [ -e /etc/init/inspeqtor.conf ]; then
  echo Stopping and disabling Upstart service
  initctl stop inspeqtor
fi
